binds:
- listeners:
  - routes:
## ==========================================================
## Stdio server: Backend and MCP Authentication
## ==========================================================
    - backends:
      - mcp:
          targets:
          - stdio:
              args:
              - '@modelcontextprotocol/server-everything'
              cmd: npx
            name: everything
      matches:
      - path:
          exact: /stdio/mcp
      - path:
          exact: /.well-known/oauth-protected-resource/stdio/mcp
      policies:
        cors:
          allowHeaders:
          - mcp-protocol-version
          - content-type
          allowOrigins:
          - '*'
        mcpAuthentication:
          audience: http://localhost:3000/stdio/mcp
          issuer: http://localhost:9000
          provider:
            custom:
              jwksUrl: http://localhost:9000/.well-known/jwks.json
          authorizationServers:
          - http://localhost:9000
          scopes:
          - read:all
          bearerMethodsSupported:
          - header
          - body
          - query
          resourceDocumentation: http://localhost:3000/stdio/docs
          resourcePolicyUri: http://localhost:3000/stdio/policies

## ==========================================================
## Remote server: Backend and MCP Authentication
## ==========================================================
    - backends:
      - mcp:
          targets:
          - mcp:
              host: mcpbin.is.solo.io
              path: /remote/mcp
              port: 443
            name: mcpbin
      matches:
      - path:
          exact: /remote/mcp
      - path:
          exact: /.well-known/oauth-protected-resource/remote/mcp
      policies:
        backendTLS: {}
        cors:
          allowHeaders:
          - mcp-protocol-version
          - content-type
          allowOrigins:
          - '*'
        mcpAuthentication:
          audience: http://localhost:3000/remote/mcp
          issuer: http://localhost:9000
          provider:
            custom:
              jwksUrl: http://localhost:9000/.well-known/jwks.json
          authorizationServers:
          - http://localhost:9000
          scopes:
          - read:all
          bearerMethodsSupported:
          - header
          - body
          - query
          resourceDocumentation: http://localhost:3000/remote/docs
          resourcePolicyUri: http://localhost:3000/remote/policies

  port: 3000
